name: photo_reader_ai
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  googleapis: ^13.2.0
  googleapis_auth: ^1.3.0
  path_provider: ^2.0.8
  sqflite: ^2.0.0+4
  shared_preferences: ^2.0.15
  http: ^1.2.2 
  convert: ^3.0.1
  audioplayers: ^6.1.0  
  cached_network_image: ^3.2.3
  camera: ^0.11.0
  flutter_tts: ^3.6.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
